# config.py

# Defaults are intentionally blank. Provide credentials via `.env` or
# `src/local_config.py` (generated by `./scripts/deploy.sh`) so secrets are
# not stored in the repository.
WIFI_SSID = ""
WIFI_PASSWORD = ""

LED_PIN = 2   # Most ESP32 boards use GPIO2 for onboard LED

# DHT22 data pin (set to a GPIO number, or None to disable)
# Example: DHT_PIN = 4
DHT_PIN = 14

# Logging rotation settings (bytes and number of backups)
# Logging rotation settings were removed — file logging is disabled.
# (Previously: LOG_MAX_BYTES, LOG_BACKUPS)

# Allow local overrides for sensitive values. Create `src/local_config.py`
# (not checked into source control) or have the deploy script generate it from
# a `.env` file so credentials are not stored in the main repo.
try:
	# local_config.py may define WIFI_SSID and WIFI_PASSWORD
	from local_config import WIFI_SSID as _LC_SSID, WIFI_PASSWORD as _LC_PASS  # type: ignore
	WIFI_SSID = _LC_SSID
	WIFI_PASSWORD = _LC_PASS
except Exception:
	# No local overrides present — keep defaults above.
	pass
